# Generated by Django 4.0 on 2022-04-08 17:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('systemStewartPlatform', '0005_law_for_platform_vibrations_law_for_platform_wave_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='system_stewart_platform',
            name='author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seriesexperiments_user_created', to='auth.user', verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='system_stewart_platform',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Добавлено'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='system_stewart_platform',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Изменено'),
        ),
        migrations.AlterField(
            model_name='law_for_platform_vibrations',
            name='stewart_platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systemStewartPlatform.stewart_platform', verbose_name='Базовый модуль'),
        ),
        migrations.AlterField(
            model_name='law_for_platform_wave',
            name='stewart_platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systemStewartPlatform.stewart_platform', verbose_name='Базовый модуль'),
        ),
        migrations.AlterField(
            model_name='stewart_platform',
            name='system_stewart_platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systemStewartPlatform.system_stewart_platform', verbose_name='Система'),
        ),
    ]
