# Generated by Django 4.0 on 2022-04-27 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('systemStewartPlatform', '0007_law_for_platform_vibrations_author_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='lawAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('law_type', models.CharField(blank=True, choices=[('Волна', 'Волна'), ('Колебания', 'Колебания')], default='Волна', max_length=10, verbose_name='Закон движения базового модуля')),
                ('time_end', models.IntegerField(verbose_name='Конечный момент времени')),
                ('x_coordinate', models.JSONField(verbose_name='Смещение по x')),
                ('y_coordinate', models.JSONField(verbose_name='Смещение по y')),
                ('z_coordinate', models.JSONField(verbose_name='Смещение по z')),
                ('γ_roll_x', models.JSONField(verbose_name='Крен(х)')),
                ('θ_pitch_y', models.JSONField(verbose_name='Тангаж(y)')),
                ('ψ_yaw_z', models.JSONField(verbose_name='Рыскание(z)')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('author', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lawAPI_user_created', to='auth.user', verbose_name='Пользователь')),
                ('stewart_platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systemStewartPlatform.stewart_platform', verbose_name='Базовый модуль')),
            ],
            options={
                'verbose_name': 'Закон движения для базового модуля',
                'verbose_name_plural': 'Законы движения для базового модуля',
            },
        ),
    ]
