# Generated by Django 4.0 on 2022-06-01 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lawAPI', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='lawAPI',
        ),
    ]
